services:
  - type: web
    name: stocksense-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: "PLACEHOLDER_FRONTEND_URL"
      - key: MONGO_URI
        value: "PLACEHOLDER_MONGO_URI"
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        value: "PLACEHOLDER_EMAIL"
      - key: EMAIL_PASS
        value: "PLACEHOLDER_PASSWORD"
      - key: STORE_NAME
        value: "StockSense Store"
