services:
  - type: web
    name: stocksense-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: "PLACEHOLDER_FRONTEND_URL"
      - key: MONGO_URI
        value: "PLACEHOLDER_MONGO_URI"
      - key: JWT_SECRET
        generateValue: true
      - key: EMAILJS_SERVICE_ID
        value: "PLACEHOLDER_SERVICE_ID"
      - key: EMAILJS_TEMPLATE_ID
        value: "PLACEHOLDER_TEMPLATE_ID"
      - key: EMAILJS_PUBLIC_KEY
        value: "PLACEHOLDER_PUBLIC_KEY"
      - key: EMAILJS_PRIVATE_KEY
        value: "PLACEHOLDER_PRIVATE_KEY"
      - key: STORE_NAME
        value: "StockSense Store"
